replicaCount: 1

frontend:
  replicaCount: 1
  image:
    repository: your-docker-repo/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  resources: {}

backend:
  replicaCount: 1
  image:
    repository: your-docker-repo/backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  resources: {}

database:
  replicaCount: 1
  image:
    repository: your-docker-repo/database
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 5432
  resources: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}