apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-database
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "miniflexcrm.fullname" . }}-database