apiVersion: v1
kind: Secret
metadata:
  name: db-connection-secret
type: Opaque
data:
  connectionString: SG9zdD1taW5pZmxleC1jcm0tZGF0YWJhc2U7UG9ydD01NDMyO1VzZXJuYW1lPWFkbWluO1Bhc3N3b3JkPWFkbWluO0RhdGFiYXNlPW1pbmlmbGV4Y3Jt