apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  connection-string: {{ "Host=miniflex-crm-database;Port=5432;Username=admin;Password=admin;Database=miniflexcrmPooling=true;Max Pool Size=100;Connection Lifetime=300;" | b64enc | quote }}