replicaCount: 1

fullnameOverride: miniflex-crm

frontend:
  replicaCount: 1
  image:
    repository: konkked/mfcrm-frontend
    pullPolicy: Always
    tag: "latest"
  service:
    type: LoadBalancer
    port: 80
  resources: {}

backend:
  replicaCount: 1
  image:
    repository: konkked/mfcrm-backend
    pullPolicy: Always
    tag: "latest"
  service:
    type: LoadBalancer
    port: 80
  resources: {}

database:
  replicaCount: 1
  image:
    repository: konkked/mfcrm-database
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: miniflexcrm
  resources: {}

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: www.miniflexcrm.com
      name: frontend
      paths:
        - path: /
          pathType: Prefix
      port:
        number: 3000
    - host: api.miniflexcrm.com
      name: backend
      paths:
        - path: /
          pathType: Prefix
      port:
        number: 5000
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}