apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-backend
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "miniflexcrm.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "miniflexcrm.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}