apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-database
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "miniflexcrm.name" . }}-database
  template:
    metadata:
      labels:
        app: {{ include "miniflexcrm.name" . }}-database
    spec:
      containers:
        - name: database
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.database.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.database.env.POSTGRES_DB }}
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}