apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: frontend.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "miniflexcrm.fullname" . }}-frontend
                port:
                  number: 80
    - host: backend.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "miniflexcrm.fullname" . }}-backend
                port:
                  number: 80