apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-frontend
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "miniflexcrm.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "miniflexcrm.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: {{ .Values.backend.base_api_uri }} # Update this to your backend API URL
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}