apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-frontend
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ include "miniflexcrm.name" . }}-frontend