apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-backend
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "miniflexcrm.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "miniflexcrm.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: MINIFLEXCRMAPI_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: miniflexcrm-jwt-secret
                  key: jwt-key
            - name: DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-connection-secret
                  key: connectionString
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}