apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniflexcrm.fullname" . }}-backend
  labels:
    {{- include "miniflexcrm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 80
  selector:
    app: {{ include "miniflexcrm.name" . }}-backend